### ISSUE TITLE
Error: 'Failed to find git repository in undefined'

### ISSUE THREAD

**Issue by dewaadiperdana** [shinnn/gulp-gh-pages#102]
I had this problem when i trying to deploy my site into my github pages. Anyone can help me please?. It also say 'Error in plugin gulp-gh-pages'.

**Comment by shinnn** [comment]
Failed at https://github.com/shinnn/gulp-gh-pages/blob/b6fe6516acb8c942908e2653e64671651d86eec5/lib/git.js#L48.
