### ISSUE TITLE
Error in plugin 'gulp-gh-pages'. "Failed to find git repository in undefined"

### ISSUE THREAD

**Issue by dewaadiperdana** [shinnn/gulp-gh-pages#103]
When i trying to deploy my website to github pages, i got this error on my command line "Error in plugin 'gulp-gh-pages'. Failed to find git repository in undefined". Is anyone can help me please?

**Comment by dewaadiperdana** [comment]
Can you just tell me how to solve this problem?, sorry i'm a beginner. By the way this is my code

```
gulp.task('deploy', function() {
  return gulp.src('./_site/**/*')
    .pipe(deploy({
      branch: 'master',
   }));
});
```

Is there anything wrong with it??. Please!!!

**Comment by shinnn** [comment]
https://github.com/shinnn/gulp-gh-pages/issues/102
