### ISSUE TITLE
custom domain erased from settings

### ISSUE THREAD

**Issue by tom-mazo** [shinnn/gulp-gh-pages#105]
When you redirect a custom domain to gh-pages (via Settings > Github Pages > Custom Domain),

every time you run the gulp-gh-pages task, the custom domain field in settings is erased and you have to type it again manually.

**Comment by timtimmytime** [comment]
Could be an issue with your CNAME file being removed each time. 
Untill it is posible with "gulp-gh-pages" this fork has addressed this issue:
https://www.npmjs.com/package/gulp-gh-pages-cname

**Comment by shinnn** [comment]
> Untill it is posible with "gulp-gh-pages

Already possible. Update your gulpfile's glob pattern to include `CNAME` file and this problem will be fixed.

@timtimmytime Do not recommend using the fork. It violates gulp plugin guidelines. ref. https://github.com/shinnn/gulp-gh-pages/pull/27#issuecomment-92115502

**Comment by tom-mazo** [comment]
Ok thanks for the responses! I just added in my dist/ directory a text file with "CNAME" as file name and the custom domain as content. It works.

**Comment by bjork24** [comment]
If anyone finds themselves here in the future, here's the solution (as suggested by @shinnn above):

This code will result in your custom domain information being erased from Github's settings:

```javascript
gulp.task('deploy', () => {
  return gulp.src('./dist')
    .pipe($.ghPages());
});
```

This is the solution:

```javascript
gulp.task('deploy', () => {
  return gulp.src(['./dist', './CNAME'])
    .pipe($.ghPages());
});
```

**Comment by francisngo** [comment]
The above doesn't work for me. I still have to manually drag and drop my CNAME from app/ to dist/. 
Also, I still don't know the order because every time I push, I have to do a git push origin master --force and then when I do a gulp deploy, a random comment gets generated ('Update 2017-01-14T01:53:13.803Z'). How do I have it so that when I gulp deploy, it's the same comment as git push?

```
gulp.task('deploy', function() {
    return gulp.src(['./dist/**/*', './CNAME']).pipe(deploy({branch: 'master'}));
});
```
