### ISSUE TITLE
Deploy is not working from travis build

### ISSUE THREAD

**Issue by kathirr007** [shinnn/gulp-gh-pages#107]
Error: Command failed: git push --set-upstream origin gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/kathirr007/HTML-Email-Rendering-issues-and-Solutions.git/'

**Comment by shinnn** [comment]
https://github.com/shinnn/gulp-gh-pages/issues/80#issuecomment-271942002
