### ISSUE TITLE
gh-pages CNAME

### ISSUE THREAD

**Issue by JosephBywater** [shinnn/gulp-gh-pages#108]
When running `gulp deploy`, the CNAME file is removed from the gh-pages branch. Is there any way to prevent this? Maybe my gulpfile is wrong? https://github.com/JosephBywater/josephbywater.co.uk/blob/master/gulpfile.js

**Comment by shinnn** [comment]
Your CNAME file is not included in this glob pattern. https://github.com/JosephBywater/josephbywater.co.uk/blob/cba5da72c07a6384ceb60c0fb2f2b72cd25b980e/gulpfile.js#L85
