### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by abloom12** [shinnn/gulp-gh-pages#116]
Im getting this Error:
TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (/Users/Ash/Documents/Projects/Websites/jherron-portfolio/node_modules/gift/lib/commit.js:145:56)
    at Function.module.exports.Commit.parse_commits (/Users/Ash/Documents/Projects/Websites/jherron-portfolio/node_modules/gift/lib/commit.js:111:21)
    at /Users/Ash/Documents/Projects/Websites/jherron-portfolio/node_modules/gift/lib/commit.js:55:39
    at ChildProcess.exithandler (child_process.js:189:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

I have my "dist" folder in the root of the directory and here is my gulp.js task below.

gulp.task('deploy', () => {
  return gulp.src('./dist/**/*')
    .pipe($.ghPages());

Im new to gulp so not sure what I'm doing wrong. I've tried removing the ./ from in front of dist in the src().

**Comment by PauloLuan** [comment]
Same error here. Using Node 8+

This is the repository that isn't working: https://github.com/ParahybaValley/landpage

**Comment by abloom12** [comment]
I deleted my gh-pages branch and then re created it on the website instead of using the command line. I then re-ran my gulp task and everything worked. I have no clue how I fixed the issue but I'm not complaining. 

Give that a try PauloLuan and see if that solves it for you. I'm using Node 6.11.4

**Comment by WhatsNewSaes** [comment]
I'm getting the same error... Just tried what @abloom12 said and that didn't work for me.

**Comment by ajmalafif** [comment]
I think it could be because of one of the dependencies, https://github.com/notatestuser/gift is out of date? Look here: https://david-dm.org/shinnn/gulp-gh-pages#info=devDependencies

Having same exact error here's my build on Travis: 
https://travis-ci.org/ajmalafif/staging

And my gulp file:
https://github.com/ajmalafif/staging/blob/master/gulpfile.js#L408

**Comment by WhatsNewSaes** [comment]
Interesting. So I just tried this on a personal repo and it worked, when I tried it in an organization that I'm invited to it didn't. Does it possibly have something to do with if you have permissions to the "settings" of a repo?

**Comment by ajmalafif** [comment]
@WhatsNewSaes hi thanks for updating. is it possible to share the repo or it's a private one? Mine is personal repo so I suspected there are different in setup or dependencies that make it work?

**Comment by renatodeleao** [comment]
Owner of an organisation, [open-source project](https://github.com/whitesmith/Flooper.js/). Also having this error.

**Comment by derekblank** [comment]
+1 to the above...org owner, admin, and [open source](https://github.com/lvhdev/lifeio-website). Same issue:

```
[17:20:53] Starting 'gh-pages'...
~/node_modules/gift/lib/commit.js:135
      _ref = /^.+? (.*) (\d+) .*$/.exec(line), m = _ref[0], actor = _ref[1], epoch = _ref[2];
                                                       ^

TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (~/node_modules/gift/lib/commit.js:135:56)
```

**Comment by gido** [comment]
The source of the problem is documented here notatestuser/gift#96
and PR #117 will fix it

**Comment by acierto** [comment]
Actually not, tried with "gift": "0.10.2" and still the issue is not gone.

<img width="954" alt="screen shot 2018-01-30 at 14 39 34" src="https://user-images.githubusercontent.com/2265094/35569098-6f1195c0-05cb-11e8-95ac-2015a0ee4ff6.png">

Test case for me:
I'm running ghPages on Jenkins (on Ubuntu), which first checkouts a revision from a master. And tried to commit generated sources based on that revision. 
Most interesting that it was working till today, I have such feeling that the problem due to some other third-party library.

**Comment by radumas** [comment]
I did `npm install --save-dev gift` and then re-ran `gulp deploy` and it worked.

**Comment by acierto** [comment]
Cool, but you know it is from the topic: "It works on my machine" :)

**Comment by jdnichollsc** [comment]
I can reproduce this issue on Mac with v6.11.4

**Comment by radumas** [comment]
> Cool, but you know it is from the topic: "It works on my machine" :)

>I don't see myself any issue on Mac, but it reproducible in 100% on Ubuntu 16.

Sorry my solution was incomplete. Forgot a step I did before... Need to upgrade `gift` within the `gulp-gh-pages` module.

```shell
cd node_modules/gulp-gh-pages/
npm install --save gift@0.10.2
cd ../../
gulp deploy
```

This worked in both Ubuntu 16.04 and a Windows 7 corporate environment

**Comment by nicothin** [comment]
Is this the problem of the version of one of the dependencies of this package?
When will this be fixed?
(it looks like it's necessary to replace a couple of digits in the dependency version)

**Comment by NikolaySolodukhin** [comment]
@nicothin gulp-gh-pages-will Use this package and everything will be ok)

**Comment by pirhoo** [comment]
It doesn't look like this repository is maintained anymore... I simply switched to `[gh-pages](https://github.com/tschaub/gh-pages)`, it's painless:

```js
var ghpages = require('gh-pages'),
             path = require('path');

gulp.task('deploy', function(cb) {
    ghpages.publish(path.join(process.cwd(), 'dist'), cb);
});
```
