### ISSUE TITLE
Task starts but doens't finish

### ISSUE THREAD

**Issue by tiagoporto** [shinnn/gulp-gh-pages#121]
I have a simple task

```
gulp.task('gh-pages', () => {
  return gulp
    .src('dist/**/*')
    .pipe(ghPages())
})
```

When It runs, it starts OK
![screen shot 2018-02-21 at 10 48 47 pm](https://user-images.githubusercontent.com/3688905/36515763-bc1d86fe-1759-11e8-8049-3641e1c89ede.png)

The `.publish` folder is created, and after nothing happens, and the task doesn't finish

![screen shot 2018-02-21 at 10 52 55 pm](https://user-images.githubusercontent.com/3688905/36515850-1c6bb292-175a-11e8-94ed-b4d2436efcc7.png)

My system
```
macOS 10.13.3 High sierra
node v6.13.0
npm v3.10.10
gulp v3.9.1
gulp-gh-pages v0.5.4
```

**Comment by jchck** [comment]
Hey @tiagoporto 
It's not very well documented but gulp-gh-pages requires gulp >= 4.0. That's what `gulp@next` is saying under [Installation in the readme](https://github.com/shinnn/gulp-gh-pages#installation), I missed it at first too.

Here's [a guide to updating ](https://www.joezimjs.com/javascript/complete-guide-upgrading-gulp-4/) but be aware that updating from Gulp v3 to v4 does contain breaking changes.
