### ISSUE TITLE
push changes to npm please

### ISSUE THREAD

**Issue by scottnath** [shinnn/gulp-gh-pages#125]
Hi @shinnn,

We've run into a `child_process` bug coming out of `gift`, but it looks like that might be fixed in your 6x version - however, npm is still on `5.4`:
https://www.npmjs.com/package/gulp-gh-pages

Could you create a release with your latest changes please?

thanks!

**Comment by shinnn** [comment]
Run `npm i gulp-gh-pages@next`.
