### ISSUE TITLE
gh-pages doesn't seem to do anything

### ISSUE THREAD

**Issue by SpectralKH** [shinnn/gulp-gh-pages#128]
I'm executing `npm run deploy` in the root of my git repository. The deploy script is defined as `"gh-pages --dist build"` inside package.json. Running the command results in this output:
![image](https://user-images.githubusercontent.com/11315492/46908188-70e82d00-cf1f-11e8-877f-ca02eb3963ff.png)

Running gh-pages in JavaScript produced the same output.

Directory structure:
```
README.md
build
    id
        test.html
    woah.css
gulpfile.js
package-lock.json
package.json
src
    id
        test.html
    woah.css
```

**Comment by shinnn** [comment]
This is not a `gh-pages` package.
