### ISSUE TITLE
gulp-util is deprecated. Will this repo be updated?

### ISSUE THREAD

**Issue by do-kevin** [shinnn/gulp-gh-pages#130]
Hey there,

I was just following tutorials for gulp deployments to GitHub pages. I keep getting `TypeError: Cannot read property '0' of null` errors. I have been unsuccessful and noticed that my terminal says _gulp-util_ is deprecated, which is what your code relies on. So is this what's causing it and will you be updating this repository?

**Comment by shinnn** [comment]
Duplicate of https://github.com/shinnn/gulp-gh-pages/issues/119
