### ISSUE TITLE
Gulp3 version requires updated Gift

### ISSUE THREAD

**Issue by mryellow** [shinnn/gulp-gh-pages#134]
It would appear `0.5.4` was never updated with patches for the broken upstream `gift` dependency. This leaves gh-pages in a broken state for Gulp3.

https://github.com/notatestuser/gift/issues/96
https://github.com/shinnn/gulp-gh-pages/issues/116
https://github.com/shinnn/gulp-gh-pages/pull/117

**Comment by mryellow** [comment]
A maintained package which works with Gulp3: https://github.com/tschaub/gh-pages

**Comment by shinnn** [comment]
Use 0.6.0-2.
