### ISSUE TITLE
Plugin broken. Can't get it to work.

### ISSUE THREAD

**Issue by harrypujols** [shinnn/gulp-gh-pages#24]
I have tried different ways of performing the task now, but it always return a stream of errors. An example of the errors is this line:
```bash
Error: Error: ENOENT, open '/var/folders/nw/mn91lw3j2pv55pn4j0nx089w0000gn/T/tmpRepo/.git/HEAD'
```
If it can be of any help, the deploy task starts at line 114 of this file: https://github.com/harrypujols/gulp/blob/master/gulpfile.js

If you check the repository, you can see that it used to use the plugin without problems previously. Thanks!

NOTE: I can't get the plugin to work in any repository, not just this one. I have tried it in 3 different computers, two Macs and a Windows 7 PC.

**Comment by shinnn** [comment]
Fixed the tmpDir problem. https://github.com/shinnn/gulp-gh-pages/issues/32#issuecomment-79054110
