### ISSUE TITLE
Optionally override everything at destination

### ISSUE THREAD

**Issue by koistya** [shinnn/gulp-gh-pages#28]
Which inits a new Git repo during a deployment and executes `git push --force {origin} {branch}`.

``` javascript
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var argv = require('minimist')(process.argv.slice(2));

gulp.task('deploy', function () {
    return gulp.src('./build/**/*')
        .pipe($.ghPages({clean: !!argv.clean}));
});
```

```
> gulp deploy --clean
```

**Comment by julien-noblet** [comment]
nice :+1:

**Comment by dcalhoun** [comment]
@rowoot I could be wrong, but my guess is that this tactic is related to #32.

**Comment by shinnn** [comment]
Thanks for the suggestion but I don't have much time and interest to implement this feature. Just delete the branch by yourself when you want to reset everything.
