### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by ColeTownsend** [shinnn/gulp-gh-pages#35]
```sh
/Users/twnsnd/Documents/gits/twnsnd.co/node_modules/gulp-gh-pages/node_modules/when/lib/decorators/unhandledRejection.js:96
		throw e;
		      ^
Error: Error: stdout maxBuffer exceeded.
```

**Comment by thedersen** [comment]
This is related to an issue in gift. Will probably be fixed when/if https://github.com/notatestuser/gift/pull/38 is accepted

**Comment by serialworm** [comment]
Not much movement on notatestuser/gift#38, or https://github.com/sentientwaffle/gift/issues/26. I guess a fork is in order.

**Comment by shinnn** [comment]
[`gift` has been updated](https://github.com/notatestuser/gift/commit/dd2ff8027a7798d82632cba77f0d4aa9d3562364). I'll update the dependencies in a few days.
