### ISSUE TITLE
Option to create commit parent from the source tree

### ISSUE THREAD

**Issue by clkao** [shinnn/gulp-gh-pages#38]
Hi, we have several projects doing the gh-pages publishing very much like gulp-gh-pages, so hopefully we can migrate over.

One of the feature in the [script](https://github.com/clkao/comap/blob/master/deploy#L38) is creating the gh-pages commit with multiple parents.  This allows finding corresponding deployment commit from source commit more easily:
![2014-10-04 6 56 31](https://cloud.githubusercontent.com/assets/69736/4515304/2cd0349c-4bb5-11e4-92c2-4ea85ce0d05e.png)

**Comment by shinnn** [comment]
> I personally have never had such a requirement

Me too.
