### ISSUE TITLE
Consider wrapping gh-pages

### ISSUE THREAD

**Issue by kflorence** [shinnn/gulp-gh-pages#43]
There is an existing fully-featured node module called "gh-pages" that does everything this plugin does and more. Would be handy to wrap it instead of having some duplicated functionality split between the two: https://github.com/tschaub/gh-pages

**Comment by peter-mouland** [comment]
love gulp - no need to wrap anything :D

**Comment by shinnn** [comment]
Relying on an external module is a good idea, but I won't choose `gh-pages` for it.
