### ISSUE TITLE
Error: Command failed: fatal: unable to read c6a8d37...

### ISSUE THREAD

**Issue by dmnd** [shinnn/gulp-gh-pages#44]
I had a really annoying issue where gulp-gh-pages would fail with the error

> Error: Command failed: fatal: unable to read c6a8d370f3e95d9110eca4a03b704bd8940ca40b

I had trouble debugging it, but once I saw it was reusing the same temporary git repo, I decided to delete it and see if that fixed things. It did.

So, I don't know exactly what was wrong with the repo, but it seems to be possible for gulp-gh-pages to end up with its temporary git repo in a corrupt state. Hopefully this issue helps someone else who runs into this.

**Comment by montecruiseto** [comment]
@mcasimir u rock big time.
ps buckley forever +++

**Comment by shinnn** [comment]
> it seems to be possible for gulp-gh-pages to end up with its temporary git repo in a corrupt state.

Fixed. https://github.com/shinnn/gulp-gh-pages/issues/32#issuecomment-79054110
