### ISSUE TITLE
Commit "introduce code linters and change coding styles" overwrote previously merged code

### ISSUE THREAD

**Issue by serialworm** [shinnn/gulp-gh-pages#52]
I've verified that https://github.com/shinnn/gulp-gh-pages/pull/47 is not in the latest code base, not sure about other changes.

**Comment by shinnn** [comment]
No. `force` option is not removed. https://github.com/shinnn/gulp-gh-pages/commit/8bd75878e862d11e30b62e9967df85e2b41d57d1#diff-168726dbe96b3ce427e7fedce31bb0bcR123

And it still passes the tests added by #47. https://github.com/shinnn/gulp-gh-pages/blob/8bd75878e862d11e30b62e9967df85e2b41d57d1/test/git-operations-spec.js#L147-L313

**Comment by serialworm** [comment]
Ok thanks, i didn't realize it was moved elsewhere.
