### ISSUE TITLE
can't push when remote is different that origin

### ISSUE THREAD

**Issue by olanod** [shinnn/gulp-gh-pages#55]
I get an error when my origin is different. `Error: Command failed: /bin/sh -c git push --set-upstream me gh-pages`

```
return gulp.src('dist/**/*')
    .pipe(ghPages({origin: 'me', force: true}));
```

the created repository has the right remote url but it's under `origin` and the command tries to push to `me` in this case.

**Comment by pwalsh** [comment]
I can confirm.

The plugin is a great idea, but the API is confusing and/or broken: seeing as my `origin` implies a `remoteUrl` - why are there two config options? 

Like the original poster, I too was trying to use the `origin` config to deploy to origins other than "origin". I found that if I simply ignore the `origin` option and just use `remoteUrl`, then things work.

**Comment by atd** [comment]
Setting `remoteUrl` instead of `origin` also worked for me.

**Comment by brunopgalvao** [comment]
Yes this worked for me:

    gulp.task('deploy', function() {
      return gulp.src('./dist/**/*')
        .pipe(ghPages({remoteUrl: 'git@github.com:organization/organization.github.io.git'}));
    });

**Comment by dbaronov** [comment]
The last answer is not only good for the situation when there is only one "origin" remove and hardcoding of remote urls is not ideal if you have cloned the main repo and working off "me" remote and then PR from "me" to "origin".

Is there a way of passing one of the remotes set in git like "origin", "me", "john", assuming I have write access to them?

**Comment by shinnn** [comment]
The `origin` option has been removed. https://github.com/shinnn/gulp-gh-pages/commit/a470b202cee9990755e4f05e76add1def62aeced. Use `remoteUrl` option instead.
