### ISSUE TITLE
Issue with symlinks

### ISSUE THREAD

**Issue by slavafomin** [shinnn/gulp-gh-pages#57]
Hello!

Thank you for this module, it works great!

However, I have an issue with symlinks. I will try to describe it.

I have a project with the following structure:

```
bower_components/foo/                 -- some dev dependency installed via Bower
lib/                                  -- some library files
demos/                                -- root directory for GH Pages
demos/foo > ../bower_components/foo/  -- directory symlink to bower component
demos/lib > ../lib                    -- directory symlink to the library
```

I'm trying to deploy `demos` directory.

However, I can't get bower component to be released on GH pages via symlink.

What could be the reason for this?

I'm talking about this repository:
https://github.com/betsol/numerous

**Comment by shinnn** [comment]
Thanks for reporting, @slavafomin.

According to [the official doc](https://help.github.com/articles/page-build-failed-file-is-a-symlink/), Github Pages doesn't support symlink. Please copy `foo` and `bar` to the `demos` folder directly.

**Comment by slavafomin** [comment]
That is exactly my problem. I want `gulp-gh-pages` to do it for me: resolve symlinks and copy all files as if no symlinks exists.

**Comment by shinnn** [comment]
According to [the plugin guideline](https://github.com/gulpjs/gulp/blob/20774ccfae315d14e693623c2768a9e2ca20af20/docs/writing-a-plugin/guidelines.md), 

> Your plugin shouldn't do things that other plugins are responsible for

Resolving symlinks should be done by another plugin.  You can create a new gulp plugin such as `gulp-replace-symlink` if needed.

**Comment by Hypercubed** [comment]
@slavafomin Did you find your solution.  Apparently gulp vs. 4 should fix this... in the meantime I am using the solution listed here to follow symbol links:   https://github.com/ben-eb/gulp-symlink#deprecation-notice

@shinnn You might want to mention something about this in your readme.

**Comment by slavafomin** [comment]
Thanks @Hypercubed for the suggestion, I'm using [ncp](https://github.com/AvianFlu/ncp) right now to first create a temporary directory with resolved symlinks.
