### ISSUE TITLE
Only adding 30 files (out of 250) to .publish directory

### ISSUE THREAD

**Issue by craigmdennis** [shinnn/gulp-gh-pages#59]
I have the following structure:

```
layouts
  | -- assets
    | -- vendor
      | --  flags
        | -- 4x3 (containing 250 svg files)
```

For some reason when I run my deploy task, only the first 30 of the 250 files are copied to the `.publish` directory. If I add them manually to the `.publish` folder then they are available for the the next deploy... but are gone again after that.

``` coffee
gulp.task 'preview', ['default'], ->
  gulp.src ['layouts/**/*']
    .pipe deploy
      branch: 'preview'
```

**Comment by shinnn** [comment]
@craigmdennis Can you create a small repository that can reproduce the problem?

**Comment by craigmdennis** [comment]
Seems to a wider issue still related to https://github.com/gulpjs/gulp/issues/552
