### ISSUE TITLE
Add only file to gh-pages (no remove)

### ISSUE THREAD

**Issue by blacroix** [shinnn/gulp-gh-pages#60]
Does this feature exist in gulp-gh-pages: https://www.npmjs.com/package/grunt-gh-pages#optionsadd ?

**Comment by ozasadnyy** [comment]
Any solutions?

**Comment by vtkalek** [comment]
The same problem. 
I can offer to make option which will make it work in a separate folder of gh-pages and remove only this folder content. Or as blacroix suggest use no-remove option.

**Comment by shinnn** [comment]
> The same problem

That's not a *problem*.

**Comment by vtkalek** [comment]
OK. If it's not a problem then can you please tell us how to keep files untouched? I want to have a folder with some examples which will open through gh_pages. But i also want to create automatic documentation to keep it in gh_pages. But when i run gulp-gh-pages it delete my examples folder.
It's a problem...

**Comment by vtkalek** [comment]
Hi, my current solution is to get rid of gulp gh-pages and use a sequence of commands.
It's a bit ugly, but working and you can do whatever you want with it:

var exec = require('child_process').exec;
var fs = require("fs");
var gutil = require('gulp-util');
var runSequence = require("run-sequence");
var del = require('del');

gulp.task('pull_gh_pages', function () {
    exec('git -C .docs pull', function (err, stdout, stderr) {console.log(stdout);console.log(stderr);});
    //return  run("git -C .docs pull").exec().pipe(gulp.dest('../output'));
});

 gulp.task('copy_docs', function () {
        return gulp.src(['docs/**/*'])
          .pipe(gulp.dest('.docs'));
    });

gulp.task('add_all_gh_pages', function (cb) {
  exec('git -C .docs add --all', function (err, stdout, stderr) {console.log(stdout);console.log(stderr);cb(err);});
});

   var doCommit = false;
//logCapture = require('gulp-log-capture');
gulp.task('commit_gh_pages', function (callback) {


    exec('git -C .docs status > node_modules/statuscheck.txt', function (err, stdout, stderr) {console.log(stdout);console.log(stderr);});

setTimeout(function() {

  fs.readFile("node_modules/statuscheck.txt", "utf-8", function(err, _data) {
        doCommit = _data.indexOf('nothing to commit')<0;
    
    del(['node_modules/statuscheck.txt'], function (err, paths) {
        //console.log('Deleted files/folders:\n', paths.join('\n'));
        });
        //console.log('Original git message: \n '+_data+ '\n end of original git message');
        if(err)
            console.log('Command exec ERROR: \n '+err);

    if(doCommit){
         console.log('Commiting changes');
        exec('git -C .docs commit -m \'automatic-documentation-update\'', function (err, stdout, stderr) {console.log(stdout);console.log(stderr);callback(err);});
  }
    else
    {
     console.log('Nothing to commit');
     return true;
    }

    });
    
}, 10000);
 // return false;            
});

gulp.task('push_gh_pages', function (cb) {
    exec('git -C .docs push', function (err, stdout, stderr) {console.log(stdout);console.log(stderr);cb(err);});
});

gulp.task('git_update_gh_pages', function(cb) {
    runSequence('pull_rebase',"build_projects","combine_internal_d_ts",'checkout_gh_pages', 'pull_gh_pages'
        , "createdocs", 'copy_docs','add_all_gh_pages','commit_gh_pages', 'push_gh_pages',cb);
});

**Comment by samjbmason** [comment]
Any solution to this I have files being deleted that are added by the GitHub API

**Comment by grtjn** [comment]
PR #81 would provide a solution for this. I installed that code for now with:

`npm install git://github.com/sharvit/gulp-gh-pages.git --save-dev`

Works like a charm for me..

**Comment by shinnn** [comment]
Sorry but I don't have enough time and interest to implement this feature.
