### ISSUE TITLE
Don't delete my files that are already in repository

### ISSUE THREAD

**Issue by ozasadnyy** [shinnn/gulp-gh-pages#62]
Hello,
First of all I want to thank you for this project. 

And I want to ask you about one problem.
I have pushed manually folder **2014** with a website from the previous year and added this folder to the `.gitignore`.
But after pushing changes using your plugin all my files have been removed.

How to overcome this problem?

**Comment by shinnn** [comment]
Duplicate: #60

**Comment by ozasadnyy** [comment]
@shinnn ok. But is there any solution for now or near future?
