### ISSUE TITLE
Can't get a callback

### ISSUE THREAD

**Issue by slavafomin** [shinnn/gulp-gh-pages#66]
Hello!

Thank you for this great module!

I'm trying to use it in my documentation deployment pipeline, however, I have a really hard time to integrate it.

I want to delete all temporary directories after deployment is done. I've tried several approaches to catch the moment when `gh-pages` finished his work, but I can't get a stable result.

Here what I've tried:

1). The documented approach using `.on('end', callback)`:

```javascript
var deploy = require('gulp-gh-pages');
return gulp.src(deployTmpPath + '/**/*')
  .pipe(deploy())
  .on('end', function () {
    console.log('Deploy finished');
  })
;
```

For some reason `gh-pages` is not deploying in this case. The callback is called immediately without any real job done.

2). The workaround using `gulp-callback`:

```javascript
var deploy = require('gulp-gh-pages');
var gcallback = require('gulp-callback');
return gulp.src(deployTmpPath + '/**/*')
  .pipe(deploy())
  .pipe(gcallback(function () {
    console.log('Deploy finished');
  }))
;
```

The callback is called several times for some reason.

---

Is there a problem with `gh-pages` handling callbacks or am I doing something wrong? Thank you!

**Comment by shinnn** [comment]
> I want to delete all temporary directories after deployment is done.

This recipe helps you. https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md

**Comment by slavafomin** [comment]
Hello @shinnn. I think you haven't understood my issue. Why the `on('end')` event is not firing properly by the `gh-pages`? I think it should work as expected.

**Comment by shinnn** [comment]
https://github.com/rvagg/through2/issues/31#issuecomment-67031971

**Comment by slavafomin** [comment]
Could you elaborate please? I don't quite understand the internals. What should I do to get a proper callback from `gh-pages`?

**Comment by shinnn** [comment]
`on('finish')`
