### ISSUE TITLE
It's working only if stream is returned to the Gulp

### ISSUE THREAD

**Issue by slavafomin** [shinnn/gulp-gh-pages#67]
Hello!

I'm still trying to isolate `gulp-gh-pages` into a simple function with callback support. I need it in order to perform multiple actions inside a single Gulp task.

Here's the code:

```javascript
var deploy = require('gulp-gh-pages');

gulp.task('demo-deploy', function (done) {

  deployFiles(function () {
    console.log('Deployed!');
    done();
  });

  /**
   * Deploys files to the server.
   */
  function deployFiles (done) {
    console.log('Starting to deploy files...');
    gulp.src(deployTmpPath + '/**/*')
      .pipe(deploy())
      .on('finish', done)
    ;
  }
});
```

For some reason if I use plugin this way it's not working at all (no actions are performed) and callback is not called at all. The only way when plugin IS working is when I return stream back to Gulp this way:

```javascript
gulp.task('demo-deploy', function () {
  return gulp.src(deployTmpPath + '/**/*')
    .pipe(deploy())
  ;
}
```

Could you tell me why this is happening and how do I isolate the plugin in it's own function? Thanks.

**Comment by shinnn** [comment]
> Could you tell me why this is happening

https://github.com/gulpjs/gulp/blob/87e8364f2c445c717ed5287b1b28c6ba02a1801f/docs/API.md#async-task-support

> to perform multiple actions inside a single Gulp task

[merge-stream](https://github.com/grncdr/merge-stream) helps you.

=========================

You should read this article again and again before open new issues to OSS projects. http://www.catb.org/esr/faqs/smart-questions.html (Especially, ["Choose your forum carefully" section](http://www.catb.org/esr/faqs/smart-questions.html#forum))
