### ISSUE TITLE
Deploy to subdirectory

### ISSUE THREAD

**Issue by pimterry** [shinnn/gulp-gh-pages#69]
I'd find it useful to deploy to a subdirectory on the target branch, without changing the rest of the existing content that's already on that branch (so this probably relates to #60).

Specific use case: I use gh-pages to host slides for various talks I give. built with [bespoke.js](https://github.com/markdalgleish/bespoke.js) and deployed with this plugin. It'd be useful to have different versions of the same built code all available at the same time in the same. E.g. deploying slides from a talk in 2014 at one conference to pimterry.github.com/talk/2014-conf1, an extended version later deployed at pimterry.github.com/talk/2014-conf2 from another conference, a rewritten version later independently deployed at pimterry.github.com/talk/2015-conf3, etc.

A) Is that possible currently? (Looks unlikely)
B) If not, is that a feature you'd be happy to add?
C) If so, could you point me in the right direction to get started doing so? Any hints?

**Comment by wcandillon** [comment]
+1
Also any pointers on how to implement this feature on this plugin would be useful.

**Comment by timaschew** [comment]
use __gulp-rename__

```
.pipe(rename(function (path) {
      path.dirname += "/your-subdirectory";
      return path;
    }))
```

**Comment by shinnn** [comment]
What @timaschew said.
