### ISSUE TITLE
Fails with two-factors authentication at github

### ISSUE THREAD

**Issue by ozasadnyy** [shinnn/gulp-gh-pages#72]
Users with enabled two-factors at github are asked for username/password which fails.

**Comment by jakubholynet** [comment]
Hi, how do I find out whether this is what is happening to me? (The last output line before gulp finished that I have is "[gh-pages] Copying files to repository".)

**Comment by jakubholynet** [comment]
How can I check that this is what is happening to me? gh-pages stops (or actually finishes) after copying pages, without doing a commit and push. Thanks!

**Comment by phawxby** [comment]
Personal access tokens!

	return gulp
		.src('./build/**/*')
    	.pipe(ghPages({
			"remoteUrl" : "https://phawxby:[Personal access token]@github.com/org/repo.git"
		}));

**Comment by tasomaniac** [comment]
Most of the two factor auth people actually using git with SSH. 
In this case having a remoteUrl like below also works perfect

```

gulp.task('gh-pages', function() {
  return gulp.src('./dist/**/*')
    .pipe(ghPages({
      "remoteUrl" : "git@github.com:gdgistanbul/devfest15.git"
    }));
});
```

**Comment by shinnn** [comment]
https://github.com/shinnn/gulp-gh-pages/issues/72#issuecomment-150573956 is the best answer.
