### ISSUE TITLE
Deploy stopped working after interrupt

### ISSUE THREAD

**Issue by Martinsos** [shinnn/gulp-gh-pages#76]
I run `gulp deploy` as usual but accidentally killed the process before it finished.
After that, I can not deploy any more! I tried deleting the repository and cloning it again, I tried pushing stuff manually to origin gh-pages (that works), but `gulp deploy` does not work.
Error that I receive:
```
[20:12:04] 'deploy' errored after 2.5 s
[20:12:04] Error in plugin 'gulp-gh-pages'
Message:
    Command failed: /bin/sh -c git rm -r .
fatal: pathspec '.' did not match any files

Details:
    killed: false
    code: 128
    signal: null
    cmd: /bin/sh -c git rm -r .

```

**Comment by Martinsos** [comment]
@shinnn you fixed this? How can I get it to work while waiting for next release, should I revert to older version of plugin?

**Comment by shinnn** [comment]
> you fixed this?

Yes. I'll release a new version after [the Windows test](https://ci.appveyor.com/project/ShinnosukeWatanabe/gulp-gh-pages/build/78) passes. 

> How can I get it to work while waiting for next release, should I revert to older version of plugin?

Yes.

**Comment by Martinsos** [comment]
@shinnn Awesome, thank you!
