### ISSUE TITLE
Cleaning .publish dir

### ISSUE THREAD

**Issue by jovpet** [shinnn/gulp-gh-pages#77]
Hi, just one question to be sure: What is your suggestion, should .publish dir need to be cleaned upon each build. I had some strange issues with ignoring some files, and I was wondering should I clean the .publish prior to build?

**Comment by dkebler** [comment]
easy enough to do with 'del' module before calling gh-pages  
https://www.npmjs.com/package/del

Or make a gulp clean task.

**Comment by shinnn** [comment]
No need to remove it in most cases.
