### ISSUE TITLE
Error doesn't break stream

### ISSUE THREAD

**Issue by neil-s** [shinnn/gulp-gh-pages#82]
When there is a git deployment error, I expect the next piped tasks to not run. However, they do seem to run.

Specifically, here is my task:
```
return gulp.src('./dist/**/*')
      .pipe(ghPages({
        branch: 'master',
      }))
      .pipe(slack("Deployed new version of website to <http://carepledge.co.uk>"));
```

The git deployment failed because I didn't have my ssh-agent running, and hence the push didn't have the necessary authentication. The slack notification was still posted, when the ideal behavior would be for the stream to get broken and for the notification to not be posted. How can I go about ensuring that this happens?

**Comment by shinnn** [comment]
Use [run-sequence](https://github.com/OverZealous/run-sequence) or [gulp 4](https://github.com/gulpjs/gulp/blob/4.0/CHANGELOG.md#400).
