### ISSUE TITLE
"repository 'undefined' does not exist"

### ISSUE THREAD

**Issue by Lomacar** [shinnn/gulp-gh-pages#86]
I followed the instructions to the letter but I get this error:

Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git clone undefined .publish"
fatal: repository 'undefined' does not exist

I am using Windows 10.

**Comment by ryantheleach** [comment]
Getting the same error, I suspect it's due to not setting up the repository remotes but I'm not 100% sure as I havn't fixed it yet

**Comment by ryantheleach** [comment]
Following the instructions (annoyingly deleted) at https://github.com/shinnn/gulp-gh-pages/commit/ce53711b46878a18cb67112a45496b3f13b7aca8#diff-04c6e90faac2675aa89e2176d2eec7d8L21 worked after setting up ssh for github.

**Comment by huguangju** [comment]
Getting the same error too, in OS X.

**Comment by naoyashiga** [comment]
I got the same error. Try this code. 

```javascript
gulp.task('deploy', function() {
  return gulp.src('./dist/**/*')
    .pipe($.ghPages({
      remoteUrl: "YOUR_REPOGITRY_URL"
    }));
});
```

**Comment by shinnn** [comment]
I cannot reproduce this problem and none of example code above is not enough clear to illustrate what happens.
