### ISSUE TITLE
stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by davetheflashguy** [shinnn/gulp-gh-pages#89]
Hey, great plugin!

Ran into an issue where I cannot publish, after about 2.5 minutes it looks like it timed out.

![image](https://cloud.githubusercontent.com/assets/1250685/13857571/cf61f19a-ec50-11e5-885d-44bd0b823848.png)

**Comment by shinnn** [comment]
https://github.com/shinnn/gulp-gh-pages/issues/65#issuecomment-124896223
