### ISSUE TITLE
File not being updated

### ISSUE THREAD

**Issue by aroach** [shinnn/gulp-gh-pages#90]
I have a README.md in my project, that I'm including in my `/build` folder via the build task for my site.

```
gulp.task('deploy', function() {
  gulp.run('build');
  return gulp.src('./build/**/*')
    .pipe(ghPages({branch: 'master'}));
});
```

However, my README.md file, that gets added into the `/build` folder, is empty in the remote repo master branch.  It almost seems like the README.md is ignored.  Any help would be appreciated.

**Comment by shinnn** [comment]
Create an example repository by which everyone can reproduce the problem.

**Comment by cjcenizal** [comment]
Since gulp executes tasks in parallel, is it possible this is a race condition? So ghPages executes before build has moved the README to the build directory?

**Comment by shinnn** [comment]
No feedback.
