### ISSUE TITLE
Option to maintain folder structure

### ISSUE THREAD

**Issue by dnasir** [shinnn/gulp-gh-pages#91]
If I had a folder structure like so:

```
dist
    | -- script.js
demo.html
```

and my deploy task like so:

```javascript
gulp.task('deploy', function() {
    return gulp.src(['dist/script.js', 'demo.html']
        .pipe(ghPages());
});
```

I expect the files to be copied to the following folder structure on my gh-pages branch:
```
dist
    | -- script.js
demo.html
```

but instead, I get this:

```
script.js
demo.html
```

It would be useful to be able to maintain the folder structure on the gh-pages branch.

**Comment by shinnn** [comment]
This is a `vinyl-fs` issue. https://www.npmjs.com/package/vinyl-fs

**Comment by dnasir** [comment]
@shinnn has it been reported?

**Comment by shinnn** [comment]
@dnasir "Option to maintain folder structure" is already implemented. Just pass the correct option to `gulp.src`.
