### ISSUE TITLE
Are you going to add 'git tag' support?

### ISSUE THREAD

**Issue by VanDalkvist** [shinnn/gulp-gh-pages#92]
I tried to use this repo for publishing to separate repo, but I was in need to make new tags for my repo. So, I didn't find any possibility to publish new tags here. Is there any chances to see here 'git tag' functionality?

**Comment by shinnn** [comment]
No, I won't. Adding a tagging feature to this plugin violates gulp plugin guideline.

**Comment by VanDalkvist** [comment]
@shinnn Could you give me details about violation of gulp plugin guideline, please?

**Comment by shinnn** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

> * Your plugin should only do **one thing**, and do it well.
>   * Avoid config options that make your plugin do completely different tasks
>   * For example: A JS minification plugin should not have an option that adds a header as well
> * Your plugin shouldn't do things that other plugins are responsible for
>   * It should not concat, gulp-concat does that
>   * It should not add headers, gulp-header does that
>   * It should not add footers, gulp-footer does that
>   * If it's a common but optional use case, document that your plugin is often used with another plugin
>   * Make use of other plugins within your plugin! This reduces the amount of code you have to write and ensures a stable ecosystem.

**Comment by VanDalkvist** [comment]
OK, thank you. But I think tagging is not a different feature. Your plugin could be used to publish not only to gh-pages branch. It could be different repository. And the purpose of a repository could be different. So, tagging is expected feature I think. Actually, when trying to use your lib, I implemented it for your repo just to check possibility with minimum coding

**Comment by ethikz** [comment]
@VanDalkvist do you have that snippet available?

**Comment by VanDalkvist** [comment]
@ethikz I just used https://github.com/tschaub/gh-pages tool onstead of this plugin

**Comment by ethikz** [comment]
@VanDalkvist well if interested in gulp-gh-pages still I was able to add tags but had to use `gulp-run` and just run git commands

```
run('git tag -a v' + res.releaseNumber + ' myBranch -m "Bump release"').exec();
run('git push --tags').exec();
```

**Comment by VanDalkvist** [comment]
@ethikz good approach, thank you for sharing :)
