### ISSUE TITLE
updating gh-pages

### ISSUE THREAD

**Issue by tatecarson** [shinnn/gulp-gh-pages#93]
Hello, 
I'm a little confused about the order of when I'm supposed to do things, and a bit new to git so it isn't helping. 

Here's my master repo: https://github.com/tatecarson/Tate-Carson/tree/master
and the 

Should I be sending new commits to my master branch before I do a gulp deploy? Or does the deploy update both branches at the same time? When I gulp deploy now it says there are no changes even though there are changes that haven't yet been reflected on the site or gh-pages branch. Just trying to figure out the best way to send updates to the site and keep everything together. 

thanks.

**Comment by tatecarson** [comment]
It seems as though a restart fixes the problem but it still might be a bug. A wrong password causes gulp gh pages to think that the files are up to date and only on a restart does it let me commit new changes. Maybe this is an issue inherent to github? I'm not really sure.

**Comment by brunogarciacosta** [comment]
Use `git config --global credential.helper wincred` to cache your credentials
As far as I know, gulp-gh-pages will only deploy your distribution folder to your gh-pages branch, so you should build the dist,  commit changes to master and then deploy to gh-pages. Or set up a task so build and deploy.

Right?

**Comment by shinnn** [comment]
What @brunogarciacosta said.
