### ISSUE TITLE
Deploy doesn't work 

### ISSUE THREAD

**Issue by vicodinchik** [shinnn/gulp-gh-pages#95]
![image](https://cloud.githubusercontent.com/assets/6984143/15979739/227e27a4-2f90-11e6-9b10-6d5d5fe8790d.png)
Usually it writes some status lines like deploying steps, but now it does nothing and finishing quiet. 

My task in gulpfile: 
`gulp.task('deploy', function(){
  gulp.src('./build/**/*')
    .pipe(gh({force: true}));
});`

**Comment by zemna** [comment]
+1

**Comment by bergren2** [comment]
@vicodinchik You need to return the stream -- not doing so means that Gulp won't wait for it to finish, and that's why your `deploy` task doesn't do anything.

    gulp.task('deploy', function(){ return gulp.src('./build/**/*') .pipe(gh({force: true})); });

**Comment by vicodinchik** [comment]
@bergren2 I will check it, but it was working without return before;

**Comment by shinnn** [comment]
What @bergren2 said.
