### ISSUE TITLE
Push to gh-pages branch does not include dot files (.nojekyll)

### ISSUE THREAD

**Issue by mattmazzola** [shinnn/gulp-gh-pages#97]
I'm using the gulp-gh-pages plugin to deploy documentation for a library.

I have it setup to deploy everything in the `docs` directory like so:
```javascript
gulp.task('ghpages', function () {
    return gulp.src(['./docs/**/*'])
        .pipe(ghPages({
            force: true,
            message: 'Update ' + moment().format('LLL')
        }));
});
```

However, this documentation is generated with files that include underscore (_) prefix which means they are ignored by jekyll (See here for more details: https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/ )

To get around this, I wanted to deploy a .nojekyll file with the docs but it seems this file is not included even when `force: true` is set.

**Does gulp-gh-pages exclude dot files by design, or is there an option to include them?**

I think a work around for me is to use the alternative `_config.yml` but those require special syntax and either directory or file glob matching which is dependent on what you upload.

If other people think this is a very common use case, it might be cool if gulp-gh-pages just had another option called `disableJekyll` and it would handle this for you.

**Comment by shinnn** [comment]
Let the glob pattern include dotfiles.

**Comment by alessandrocapra** [comment]
Hi @shinnn , could you please explain how to do this? I'm having the same issue, cannot figure out how to do it

**Comment by alessandrocapra** [comment]
Ah perfect! I think this will be helpful for others as well 👍
