### ISSUE TITLE
Deploy a subfolder on user.github.io

### ISSUE THREAD

**Issue by smerth** [shinnn/gulp-gh-pages#99]
Hello there,

According to your npm page I should change the branch to "master" when deploying on my user.github.io repo.

So I changed my gulp task as follows:

```
function pushghpages() {
  return gulp.src('./dist/**/*')
    .pipe(ghPages({ branch: "master" }));
}
```

Now the code in my .dist folder is pushed to the master branch.  My gh-pages branch exists but nothing is pushed to it.

I can view the site at user.github.io...

However, I want my project code for user.github.io on the user.github.io maser branch.  I want the dist folder (which is a subfolder of the project) to be pushed to gh-pages branch and I want to be able to view the site at: user.github.io

That is in fact how the deployment works with a regular project repo.  I have used gulp-ch-pages on to deploy the list subfolder of a project on the master branch to the gh-pages branch of a repo and then I can view the site at user.github.io/project.

That's brilliant, and I love the plugin.

But I can't get the same setup to work on the organization repo: i.e. user.github.io

Can you help me figure this out???

**Comment by shinnn** [comment]
https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages

> I can't get the same setup to work on the organization repo: i.e. user.github.io

That's how User & Organization Pages works and unconfigurable by end users.

**Comment by smerth** [comment]
Thanks.
